//TODO CREATE A CLASS WITH SINGLETON DESGIN PATTERN 
//TODO CREATE A LIST INSIDE THE CLASS
//TODO STORE ALL CHAT IN THE LIST 
//TODO CREATE REGISTER_TO_SOCKET(ID:STRING|INT|UUID)
//TODO CREATE LEAVE_FROM_SOCKET(ID:STRING|INT|UUID)